name: Build UABEA Cross-Platform

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild (Windows only)
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1

    - name: Build UABEA
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          dotnet publish UABEAvalonia.sln -c Release -r linux-x64 --self-contained -o ./publish/linux
        else
          msbuild UABEAvalonia.sln /restore /p:Configuration=Release /p:RuntimeIdentifier=win-x64 /p:SelfContained=true /p:OutputPath=./publish/windows
        fi

    - name: Package as Zip
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          zip -r uabea-ubuntu.zip ./publish/ubuntu
        else
          zip -r uabea-windows.zip ./publish/windows
        fi

    - name: Upload Ubuntu Zip
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: uabea-ubuntu
        path: uabea-ubuntu.zip

    - name: Upload Windows Zip
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: uabea-windows
        path: uabea-windows.zip
