name: Build UABEA Cross-Platform

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2022]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild (Windows only)
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1.1

    # Build Step - Different Commands for Each OS
    - name: Build UABEA (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        dotnet publish UABEAvalonia.sln -c Release -r linux-x64 --self-contained -o ./publish/ubuntu

    - name: Build UABEA (Windows)
      if: runner.os == 'Windows'
      run: |
        msbuild UABEAvalonia.sln /restore /p:Configuration=Release /p:RuntimeIdentifier=win-x64 /p:SelfContained=true /p:OutputPath=./publish/windows

    # Package Step - Different Commands for Each OS
    - name: Package as Zip (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        zip -r uabea-ubuntu.zip ./publish/ubuntu

    - name: Package as Zip (Windows)
      if: runner.os == 'Windows'
      run: |
        Compress-Archive -Path ./publish/windows -DestinationPath uabea-windows.zip

    # Upload Artifacts
    - name: Upload Ubuntu Zip
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v3
      with:
        name: uabea-ubuntu
        path: uabea-ubuntu.zip

    - name: Upload Windows Zip
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: uabea-windows
        path: uabea-windows.zip
